"""empty message

Revision ID: 237d3e110a99
Revises: caa7d41c60ac
Create Date: 2018-10-22 23:06:17.284924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237d3e110a99'
down_revision = 'caa7d41c60ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'board_id')
    # ### end Alembic commands ###
