"""empty message

Revision ID: 54aa1c1b8beb
Revises: 6b6e3fdc721d
Create Date: 2018-10-08 02:32:18.208097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54aa1c1b8beb'
down_revision = '6b6e3fdc721d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', '_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', 'username')
    # ### end Alembic commands ###
