"""empty message

Revision ID: 656c591cb566
Revises: dff6edabb475
Create Date: 2018-10-08 01:55:57.741315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '656c591cb566'
down_revision = 'dff6edabb475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmsuser', sa.Column('_password', sa.String(length=50), nullable=False))
    op.drop_column('cmsuser', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmsuser', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cmsuser', '_password')
    # ### end Alembic commands ###
