"""empty message

Revision ID: 6b6e3fdc721d
Revises: 0de4390a88fe
Create Date: 2018-10-08 02:31:42.150756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b6e3fdc721d'
down_revision = '0de4390a88fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_username', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', '_username')
    # ### end Alembic commands ###
