"""empty message

Revision ID: b586e7f473e4
Revises: 54aa1c1b8beb
Create Date: 2018-10-08 02:34:35.272754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b586e7f473e4'
down_revision = '54aa1c1b8beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
