"""empty message

Revision ID: d253153a2f63
Revises: 76dbd66d1115
Create Date: 2018-10-19 18:14:48.030458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd253153a2f63'
down_revision = '76dbd66d1115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('crate_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'crate_time')
    # ### end Alembic commands ###
